version: "3.3"

services:

  retrieval:
    image: ${DOCKER_RETRIEVAL} 
    networks:
      - nosql_net
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      PLUGINS: "[ { id: wds_p52_connector } ]" 
    ports:
      - ${CONNECTOR_PORT}:80
      - ${RETRIEVAL_PORT}:80 
    deploy:
      restart_policy:
        condition: on-failure

networks:
  nosql_net: 
    external: true 
