version: "3.3"

services:

  retrieval:
    image: ${DOCKER_RETRIEVAL} 
    networks:
      - nosql_net 
      - net
    environment:
      - DB_CONNECTION
    ports:
      - ${RETRIEVAL_PORT}:80
    deploy:
      restart_policy:
        condition: on-failure

  p52connector:
    image: ${DOCKER_P52_CONNECTOR} 
    networks:
      - net
    environment:
       RETRIEVAL_URL: "http://retrieval"
    ports:
      - ${CONNECTOR_PORT}:80
    deploy:
      restart_policy:
        condition: on-failure

networks:
  net: 
    driver: overlay 
  nosql_net: 
    external: true 
